name: Build and upload to PyPI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        pytorch_version: [2.6.0, 2.7.1, 2.8.0, 2.9.1, 2.10.0, 2.11.0, 2.12.1]
        cuda_version: ["cpu", "cu126", "cu128"]
        include:
          - os: ubuntu-latest
            platform: manylinux_x86_64
          - os: macos-latest
            platform: macosx_arm64
          - cuda_version: "cu126"
            torch_cuda_arch_list: "5.0;6.0;7.0;7.5;8.0;8.6;9.0"
            cuda_repo: https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
            cuda_package: cuda-toolkit-12-6
          - cuda_version: "cu128"
            torch_cuda_arch_list: "7.5;8.0;8.6;9.0;10.0;12.0+PTX"
            cuda_repo: https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
            cuda_package: cuda-toolkit-12-8
          - os: ubuntu-latest
            platform: manylinux_x86_64
            pytorch_version: 2.6.0
            cuda_version: "cu124"
            manylinux_image: manylinux2014
            torch_cuda_arch_list: "5.0;6.0;7.0;7.5;8.0;8.6;9.0"
            cuda_repo: https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo
            cuda_package: cuda-toolkit-12-4
          - os: ubuntu-latest
            platform: manylinux_x86_64
            pytorch_version: 2.12.1
            cuda_version: "cu130"
            torch_cuda_arch_list: "7.5;8.0;8.6;9.0;10.0;12.0+PTX"
            cuda_repo: https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
            cuda_package: cuda-toolkit-13-0
        exclude:
          - os: macos-latest
            cuda_version: "cu126"
          - os: macos-latest
            cuda_version: "cu128"
          - os: ubuntu-latest
            pytorch_version: 2.6.0
            cuda_version: "cu128"
          - os: ubuntu-latest
            pytorch_version: 2.12.1
            cuda_version: "cu128"

    steps:
      - uses: actions/checkout@v7

      - name: Add PyTorch build tag to package version
        shell: bash
        run: |
          TORCH_VERSION="$(echo "pt${{ matrix.pytorch_version }}" | sed 's/..$//' | sed 's/\.//g')"
          LOCAL_VERSION="${TORCH_VERSION}${{ matrix.cuda_version }}"

          sed -i.bak -E "s/version=\"([^\"]+)\"/version=\"\1+${LOCAL_VERSION}\"/" setup.py
          rm setup.py.bak

      - name: Build wheels
        uses: pypa/cibuildwheel@v4.1.0
        env:
          CIBW_BUILD: cp310-${{ matrix.platform }}
          CIBW_BUILD_FRONTEND: "build; args: --no-isolation"
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_BEFORE_ALL_LINUX: |
            if [ "${{ matrix.cuda_version }}" != "cpu" ]; then
              curl "${{ matrix.cuda_repo }}" -o /etc/yum.repos.d/cuda.repo
              yum clean all
              yum -y install ${{ matrix.cuda_package }}
            fi
            yum -y install gcc-toolset-13-gcc gcc-toolset-13-gcc-c++
          # https://github.com/pytorch/test-infra/blob/main/tools/pkg-helpers/pytorch_pkg_helpers/cuda.py
          # not sure if all the variables are needed
          # CC, CXX, CUDAHOSTCXX: manylinux_2_28 has gcc 14, which is not compatible with cuda 12.6.
          # see: https://github.com/pytorch/pytorch/issues/152426
          CIBW_ENVIRONMENT_LINUX: >
            CUDA_HOME=/usr/local/cuda
            CUDA_PATH=/usr/local/cuda
            CPATH=/usr/local/cuda/include:$CPATH
            TORCH_CUDA_ARCH_LIST="${{ matrix.torch_cuda_arch_list }}"
            CC=/opt/rh/gcc-toolset-13/root/usr/bin/gcc
            CXX=/opt/rh/gcc-toolset-13/root/usr/bin/g++
            CUDAHOSTCXX=/opt/rh/gcc-toolset-13/root/usr/bin/g++
          CIBW_ENVIRONMENT: >
            TORCH_INDEX_URL="https://download.pytorch.org/whl/${{ matrix.cuda_version }}"
          CIBW_BEFORE_BUILD: |
            pip install --upgrade pip setuptools wheel ninja
            pip install --index-url "$TORCH_INDEX_URL" "torch==${{ matrix.pytorch_version }}"
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          # see https://github.com/pytorch/ao/blob/main/packaging/post_build_script.sh
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: >
            auditwheel repair
            --exclude libtorch.so
            --exclude libtorch_python.so
            --exclude libtorch_cuda.so
            --exclude libtorch_cpu.so
            --exclude libc10.so
            --exclude libc10_cuda.so
            --exclude libcudart.so.12
            --exclude libcudart.so.11.0
            -w {dest_dir} {wheel}
          CIBW_BEFORE_TEST: |
            pip install --force-reinstall --index-url "$TORCH_INDEX_URL" "torch==${{ matrix.pytorch_version }}"
          # setuptools required by `import from torch.testing._internal.common_utils import TestCase`
          CIBW_TEST_REQUIRES: pytest expecttest scipy setuptools
          CIBW_TEST_COMMAND: pytest {project}/tests

      - name: Move wheels into S3 layout
        run: |
          mkdir -p dist/torch-${{ matrix.pytorch_version }}+${{ matrix.cuda_version }}
          mv wheelhouse/*.whl dist/torch-${{ matrix.pytorch_version }}+${{ matrix.cuda_version }}/

      - uses: actions/upload-artifact@v7
        with:
          name: cibw-wheels-${{ matrix.os }}-torch${{ matrix.pytorch_version }}-${{ matrix.cuda_version }}
          path: dist

  upload_wheels:
    name: Upload wheels to S3 bucket
    needs: [build_wheels]
    runs-on: ubuntu-latest
    # Need ID token write permission to use OIDC
    permissions:
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: cibw-wheels-*
          path: dist
          merge-multiple: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::175686757962:role/github-actions-s3-upload
          aws-region: us-east-2

      - name: Additional steps
        run: |
          aws s3 sync dist "s3://torch-bessel/whl"

  publish_pypi:
    name: Publish source distribution to PyPI
    needs: [build_wheels, upload_wheels]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Build source distribution
        run: |
          python -m pip install build
          python -m build --sdist

      - name: Publish source distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1